### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 70813: ordinal not in range(128)

### ISSUE THREAD

**Issue by timonweb** [amol-/dukpy#12] opened 2017-01-27 09:50 UTC
I get the error 

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 70813: ordinal not in range(128)

every time I try to run any JS code via `dukpy.babel_compile`

Here's an example snippet:

`dukpy.babel_compile("var o = {'value': 5}; o['value'] += 7; o")`

Env: Python 3.4 with virtualenv

**Comment by webknjaz** [comment] 2017-03-07 11:19
@timonweb try setting any UTF-8 aware locale using environment variables.

**Comment by amol-** [comment] 2018-04-09 21:44
Problem is caused by the fact that the babel compiler is UTF8 javascript, so when dukpy tries to read the compiler to run it it will receive utf8 data, but Python3.X decodes data according to the system locale.

Your system locale is probably ascii ("C"?) so Python is trying to decode the babel source code as plain ascii and failing.

I hope to fix this for next release as it's also a requirement for windows systems

**Comment by amol-** [comment] 2018-04-18 21:43
This should have been fixed in 0.2.0 release.

**Closed by amol-** 2018-04-18 21:43 UTC
